### ISSUE TITLE
No more "solved" icon in section view after upgrading to Elkarte 1.1.7

### ISSUE THREAD

**Issue by sjpp** [Spuds/Elk-Solved-Topics#5]
Hi,

I am the admin of an Elkarte forum and I have been using this (very convenient) plugin for 2 years.
After upgrading to Elkarte 1.1.7 the icon showing that a topic is resolved has disappeared in the section view. If you go inside the topic, it is indeed marked as solved.

Example:
- [this topic](https://www.alionet.org/index.php?topic=640.0) has been marked as solved
- but in [its section view](https://www.alionet.org/index.php?board=3.40) there is no more icon showing its "solved" status.

Thank you for your attention on this issue, let me know if I can provide more information.

**Comment by Spuds** [comment]
That is a bug.  

The latest version used a new icon name ```check``` vs ```solved``` in order to use an existing ElkArte SVG file.  I'm not sure how I want to approach the formal fix, have to think about it some, but for you the easy thing to do is:

edit ```themes/default/css/icons_svg.css``` In that file find the line that reads
```.i-check::before, .i-post_moderation_allow::before {```  change it so it reads
```.i-check::before, .i-post_moderation_allow::before, .i-solved::before {```
That will allow the icon to appear in the section view.

**Comment by sjpp** [comment]
Thanks a lot for this super quick answer :)
Changing the line that you mentioned (line 87 in my version of the default theme .css file) fixes the issue.

Note for future readers: do not forget the dot before `i-solved::before`:

`.i-check::before, .i-post_moderation_allow::before, .i-solved::before {
`

Thanks again !
